-- Add AI-generated flag to posts table
-- This allows us to track and display posts created by the content bot

ALTER TABLE posts
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE;

-- Add index for filtering AI-generated posts
CREATE INDEX IF NOT EXISTS posts_is_ai_generated_idx ON posts(is_ai_generated);

-- Add comment
COMMENT ON COLUMN posts.is_ai_generated IS 'Flag indicating if this post was generated by AI content bot';

-- Create bot user profile
-- This will be the owner of all AI-generated posts
INSERT INTO auth.users (
  id,
  email,
  encrypted_password,
  email_confirmed_at,
  created_at,
  updated_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  role
)
VALUES (
  '00000000-0000-0000-0000-000000000002'::uuid,
  'contentbot@findsomeone.app',
  crypt('RANDOM_SECURE_PASSWORD_CHANGE_ME', gen_salt('bf')),
  now(),
  now(),
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"FindSomeone Bot"}'::jsonb,
  false,
  'authenticated'
)
ON CONFLICT (id) DO NOTHING;

-- Create bot profile
INSERT INTO profiles (
  id,
  email,
  full_name,
  bio,
  verified,
  created_at,
  updated_at
)
VALUES (
  '00000000-0000-0000-0000-000000000002'::uuid,
  'contentbot@findsomeone.app',
  'FindSomeone Bot',
  'Automatyczny bot generujący przykładowe ogłoszenia. Treści wygenerowane przez AI.',
  true,
  now(),
  now()
)
ON CONFLICT (id) DO NOTHING;
